# Generated by Django 4.1.3 on 2022-11-29 22:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ingredients', models.TextField()),
                ('mode_prepare', models.TextField()),
                ('time_prepare', models.IntegerField()),
                ('income', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('date_time_created', models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 29, 19, 49, 34, 575998))),
            ],
        ),
    ]
