# Generated by Django 4.1.3 on 2022-11-30 03:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peoples', '0001_initial'),
        ('recipe', '0002_alter_recipe_date_time_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='people',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='peoples.people'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='date_time_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 30, 0, 46, 8, 674149)),
        ),
    ]
