# Generated by Django 4.1.3 on 2022-11-30 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_recipe_published_alter_recipe_date_time_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%d/%m/%Y/'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='date_time_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 30, 8, 53, 45, 93391)),
        ),
    ]
