# Generated by Django 4.1.3 on 2022-11-30 03:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='date_time_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 30, 0, 35, 45, 306002)),
        ),
    ]
