# Generated by Django 4.1.3 on 2022-12-01 11:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0005_recipe_photo_alter_recipe_date_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='date_time_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 1, 8, 53, 27, 400321)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='people',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
